#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AN_PlayFootstepAnimals

#include "Basic.hpp"

#include "E_AnimalFoot_structs.hpp"
#include "Engine_classes.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass AN_PlayFootstepAnimals.AN_PlayFootstepAnimals_C
// 0x0008 (0x0040 - 0x0038)
class UAN_PlayFootstepAnimals_C final : public UAnimNotify
{
public:
	E_AnimalFoot                                  Foot;                                              // 0x0038(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	struct FVector GetFeetLocation(class USceneComponent*& Mesh) const;
	void GetStandingMaterial(class USkeletalMeshComponent* OwnerSkelet, EPhysicalSurface* PhysMat) const;
	void IsPlayerCharacter(class USkeletalMeshComponent* OwnerSkelet, bool* IsPlayerControlled) const;
	bool Received_Notify(class USkeletalMeshComponent* MeshComp, class UAnimSequenceBase* Animation, const struct FAnimNotifyEventReference& EventReference) const;
	class UNiagaraSystem* SelectNiagaraForSurface(EPhysicalSurface Surface) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AN_PlayFootstepAnimals_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AN_PlayFootstepAnimals_C")
	}
	static class UAN_PlayFootstepAnimals_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAN_PlayFootstepAnimals_C>();
	}
};
DUMPER7_ASSERTS_UAN_PlayFootstepAnimals_C;

}

