#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DayNightControllerInterface

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_DayNightControllerInterface.BP_DayNightControllerInterface_C.PausedCycle
// 0x0008 (0x0008 - 0x0000)
struct BP_DayNightControllerInterface_C_PausedCycle final
{
public:
	class UGenericQuest*                          Quest;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DayNightControllerInterface_C_PausedCycle;

// Function BP_DayNightControllerInterface.BP_DayNightControllerInterface_C.UnPausedCycle
// 0x0008 (0x0008 - 0x0000)
struct BP_DayNightControllerInterface_C_UnPausedCycle final
{
public:
	class UGenericQuest*                          Quest;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DayNightControllerInterface_C_UnPausedCycle;

}

