#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode

#include "Basic.hpp"

#include "BP_GameMode_classes.hpp"
#include "BP_GameMode_parameters.hpp"


namespace SDK
{

// Function BP_GameMode.BP_GameMode_C.DisablePlayerInput
// (BlueprintCallable, BlueprintEvent)

void ABP_GameMode_C::DisablePlayerInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_C", "DisablePlayerInput");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode.BP_GameMode_C.EnablePlayerInput
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EInputType                              InputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_C::EnablePlayerInput(EInputType InputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_C", "EnablePlayerInput");

	Params::BP_GameMode_C_EnablePlayerInput Parms{};

	Parms.InputType = InputType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode.BP_GameMode_C.ExecuteUbergraph_BP_GameMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_C::ExecuteUbergraph_BP_GameMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_C", "ExecuteUbergraph_BP_GameMode");

	Params::BP_GameMode_C_ExecuteUbergraph_BP_GameMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode.BP_GameMode_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GameMode_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode.BP_GameMode_C.SetInputPreset
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PresetIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_C::SetInputPreset(int32 PresetIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_C", "SetInputPreset");

	Params::BP_GameMode_C_SetInputPreset Parms{};

	Parms.PresetIndex = PresetIndex;

	UObject::ProcessEvent(Func, &Parms);
}

}

