#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode_DLC_MainMenu

#include "Basic.hpp"

#include "BP_GameMode_DLC_MainMenu_classes.hpp"
#include "BP_GameMode_DLC_MainMenu_parameters.hpp"


namespace SDK
{

// Function BP_GameMode_DLC_MainMenu.BP_GameMode_DLC_MainMenu_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GameMode_DLC_MainMenu_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_DLC_MainMenu_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode_DLC_MainMenu.BP_GameMode_DLC_MainMenu_C.InitMainMenuWidget
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_GameMode_DLC_MainMenu_C::InitMainMenuWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_DLC_MainMenu_C", "InitMainMenuWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode_DLC_MainMenu.BP_GameMode_DLC_MainMenu_C.ExecuteUbergraph_BP_GameMode_DLC_MainMenu
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_DLC_MainMenu_C::ExecuteUbergraph_BP_GameMode_DLC_MainMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_DLC_MainMenu_C", "ExecuteUbergraph_BP_GameMode_DLC_MainMenu");

	Params::BP_GameMode_DLC_MainMenu_C_ExecuteUbergraph_BP_GameMode_DLC_MainMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

