#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractionComponent

#include "Basic.hpp"

#include "BP_InteractionComponent_classes.hpp"
#include "BP_InteractionComponent_parameters.hpp"


namespace SDK
{

// Function BP_InteractionComponent.BP_InteractionComponent_C.BPI_getDialogComponent
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_Ink_Dialog_Component_C**      Ref_DialogComponent                                    (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_InteractionComponent_C::BPI_getDialogComponent(class UBP_Ink_Dialog_Component_C** Ref_DialogComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "BPI_getDialogComponent");

	Params::BP_InteractionComponent_C_BPI_getDialogComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Ref_DialogComponent != nullptr)
		*Ref_DialogComponent = Parms.Ref_DialogComponent;
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.CloseInteractPrompt
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_InteractionComponent_C::CloseInteractPrompt()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "CloseInteractPrompt");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.ExecuteUbergraph_BP_InteractionComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InteractionComponent_C::ExecuteUbergraph_BP_InteractionComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "ExecuteUbergraph_BP_InteractionComponent");

	Params::BP_InteractionComponent_C_ExecuteUbergraph_BP_InteractionComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.InteractWithObject
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_InteractionComponent_C::InteractWithObject()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "InteractWithObject");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_InteractionComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.SetInteractionObject
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BaseTrigger_C*                Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_InteractionComponent_C::SetInteractionObject(class ABP_BaseTrigger_C* Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "SetInteractionObject");

	Params::BP_InteractionComponent_C_SetInteractionObject Parms{};

	Parms.Object = Object;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_InteractionComponent.BP_InteractionComponent_C.ShowInteractPrompt
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EInteractionType                        InteractionType                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_InteractionComponent_C::ShowInteractPrompt(EInteractionType InteractionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractionComponent_C", "ShowInteractPrompt");

	Params::BP_InteractionComponent_C_ShowInteractPrompt Parms{};

	Parms.InteractionType = InteractionType;

	UObject::ProcessEvent(Func, &Parms);
}

}

