#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NinjaLive_Snow_FluidSim

#include "Basic.hpp"

#include "NinjaLive_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NinjaLive_Snow_FluidSim.BP_NinjaLive_Snow_FluidSim_C
// 0x0018 (0x0580 - 0x0568)
class ABP_NinjaLive_Snow_FluidSim_C : public ANinjaLive_C
{
public:
	class UNiagaraComponent*                      NiagaraComponent;                                  // 0x0568(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UVolumeSmokeComponent_C*                VolumeSmokeComponent1;                             // 0x0570(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UVolumeSmokeComponent_C*                VolumeSmokeComponent;                              // 0x0578(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NinjaLive_Snow_FluidSim_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NinjaLive_Snow_FluidSim_C")
	}
	static class ABP_NinjaLive_Snow_FluidSim_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NinjaLive_Snow_FluidSim_C>();
	}
};
DUMPER7_ASSERTS_ABP_NinjaLive_Snow_FluidSim_C;

}

