#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AICVillage

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPI_AICVillage.BPI_AICVillage_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_AICVillage_C final
{
public:
	void GenIndex(int32* Index_0);
	void GetIndex(int32* Index_0);
	void Introvert();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_AICVillage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_AICVillage_C")
	}
	static class IBPI_AICVillage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_AICVillage_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
DUMPER7_ASSERTS_IBPI_AICVillage_C;

}

