#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_ActivateEffect

#include "Basic.hpp"

#include "BTTask_ActivateEffect_classes.hpp"
#include "BTTask_ActivateEffect_parameters.hpp"


namespace SDK
{

// Function BTTask_ActivateEffect.BTTask_ActivateEffect_C.ExecuteUbergraph_BTTask_ActivateEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_ActivateEffect_C::ExecuteUbergraph_BTTask_ActivateEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_ActivateEffect_C", "ExecuteUbergraph_BTTask_ActivateEffect");

	Params::BTTask_ActivateEffect_C_ExecuteUbergraph_BTTask_ActivateEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_ActivateEffect.BTTask_ActivateEffect_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBTTask_ActivateEffect_C::ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_ActivateEffect_C", "ReceiveExecuteAI");

	Params::BTTask_ActivateEffect_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController = OwnerController;
	Parms.ControlledPawn = ControlledPawn;

	UObject::ProcessEvent(Func, &Parms);
}

}

