#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CME_GiveHonor

#include "Basic.hpp"


namespace SDK::Params
{

// Function CME_GiveHonor.CME_GiveHonor_C.Cheat_GiveHonor
// 0x0018 (0x0018 - 0x0000)
struct CME_GiveHonor_C_Cheat_GiveHonor final
{
public:
	int32                                         HonorPoints;                                       // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAC_SkillTree_C*                        CallFunc_GetComponentByClass_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CME_GiveHonor_C_Cheat_GiveHonor;

}

