#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CME_GiveAllSkillTreeItems

#include "Basic.hpp"

#include "CME_GiveAllSkillTreeItems_classes.hpp"
#include "CME_GiveAllSkillTreeItems_parameters.hpp"


namespace SDK
{

// Function CME_GiveAllSkillTreeItems.CME_GiveAllSkillTreeItems_C.Cheat_GiveAllSkillTreeItems
// (Exec, Public, BlueprintCallable, BlueprintEvent)

void UCME_GiveAllSkillTreeItems_C::Cheat_GiveAllSkillTreeItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CME_GiveAllSkillTreeItems_C", "Cheat_GiveAllSkillTreeItems");

	UObject::ProcessEvent(Func, nullptr);
}

}

