#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DetectedStealth_GE

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DetectedStealth_GE.DetectedStealth_GE_C
// 0x0000 (0x0A70 - 0x0A70)
class UDetectedStealth_GE_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DetectedStealth_GE_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DetectedStealth_GE_C")
	}
	static class UDetectedStealth_GE_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDetectedStealth_GE_C>();
	}
};
DUMPER7_ASSERTS_UDetectedStealth_GE_C;

}

