#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HeavyAttack_NewBattleSystem

#include "Basic.hpp"

#include "GA_HeavyAttack_NewBattleSystem_classes.hpp"
#include "GA_HeavyAttack_NewBattleSystem_parameters.hpp"


namespace SDK
{

// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.AddComboStack
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::AddComboStack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "AddComboStack");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.Added_E8B8EDAC45B2687AE758E7AAA2D48FE5
// (BlueprintCallable, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::Added_E8B8EDAC45B2687AE758E7AAA2D48FE5()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "Added_E8B8EDAC45B2687AE758E7AAA2D48FE5");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.CalculateCritChance
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UGA_HeavyAttack_NewBattleSystem_C::CalculateCritChance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "CalculateCritChance");

	Params::GA_HeavyAttack_NewBattleSystem_C_CalculateCritChance Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.CalculateDamage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::CalculateDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "CalculateDamage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.DealDamage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::DealDamage(class AActor* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "DealDamage");

	Params::GA_HeavyAttack_NewBattleSystem_C_DealDamage Parms{};

	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.ExecuteUbergraph_GA_HeavyAttack_NewBattleSystem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::ExecuteUbergraph_GA_HeavyAttack_NewBattleSystem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "ExecuteUbergraph_GA_HeavyAttack_NewBattleSystem");

	Params::GA_HeavyAttack_NewBattleSystem_C_ExecuteUbergraph_GA_HeavyAttack_NewBattleSystem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.FilterBlockingHits
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FHitResult>&              Hits                                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// bool*                                   Hit                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<struct FHitResult>*              SuccesfulHits                                          (Parm, OutParm, ContainsInstancedReference)

void UGA_HeavyAttack_NewBattleSystem_C::FilterBlockingHits(TArray<struct FHitResult>& Hits, bool* Hit, TArray<struct FHitResult>* SuccesfulHits)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "FilterBlockingHits");

	Params::GA_HeavyAttack_NewBattleSystem_C_FilterBlockingHits Parms{};

	Parms.Hits = std::move(Hits);

	UObject::ProcessEvent(Func, &Parms);

	Hits = std::move(Parms.Hits);

	if (Hit != nullptr)
		*Hit = Parms.Hit;

	if (SuccesfulHits != nullptr)
		*SuccesfulHits = std::move(Parms.SuccesfulHits);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.GetComboMultiplier
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32                                   ComboAmount                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::GetComboMultiplier(int32 ComboAmount, double* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "GetComboMultiplier");

	Params::GA_HeavyAttack_NewBattleSystem_C_GetComboMultiplier Parms{};

	Parms.ComboAmount = ComboAmount;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.IsCritHit
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UGA_HeavyAttack_NewBattleSystem_C::IsCritHit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "IsCritHit");

	Params::GA_HeavyAttack_NewBattleSystem_C_IsCritHit Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "K2_OnEndAbility");

	Params::GA_HeavyAttack_NewBattleSystem_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.ManageBloodSplashes
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           HitActor                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::ManageBloodSplashes(class AActor* HitActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "ManageBloodSplashes");

	Params::GA_HeavyAttack_NewBattleSystem_C_ManageBloodSplashes Parms{};

	Parms.HitActor = HitActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.ManageWeaponTrail
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Spawn                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UseTrail2                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::ManageWeaponTrail(bool Spawn, bool UseTrail2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "ManageWeaponTrail");

	Params::GA_HeavyAttack_NewBattleSystem_C_ManageWeaponTrail Parms{};

	Parms.Spawn = Spawn;
	Parms.UseTrail2 = UseTrail2;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.NotifyCallback
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    End_                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::NotifyCallback(class FName Selection, const class UAnimNotifyState* AnimNotifyState, bool End_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "NotifyCallback");

	Params::GA_HeavyAttack_NewBattleSystem_C_NotifyCallback Parms{};

	Parms.Selection = Selection;
	Parms.AnimNotifyState = AnimNotifyState;
	Parms.End_ = End_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnBlendOut_4AA96CBA4011B106500E1198864653DB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnBlendOut_4AA96CBA4011B106500E1198864653DB(class FName NotifyName, const class UAnimNotifyState* AnimNotifyState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnBlendOut_4AA96CBA4011B106500E1198864653DB");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnBlendOut_4AA96CBA4011B106500E1198864653DB Parms{};

	Parms.NotifyName = NotifyName;
	Parms.AnimNotifyState = AnimNotifyState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnCompleted_4AA96CBA4011B106500E1198864653DB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnCompleted_4AA96CBA4011B106500E1198864653DB(class FName NotifyName, const class UAnimNotifyState* AnimNotifyState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnCompleted_4AA96CBA4011B106500E1198864653DB");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnCompleted_4AA96CBA4011B106500E1198864653DB Parms{};

	Parms.NotifyName = NotifyName;
	Parms.AnimNotifyState = AnimNotifyState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnInterrupted_4AA96CBA4011B106500E1198864653DB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnInterrupted_4AA96CBA4011B106500E1198864653DB(class FName NotifyName, const class UAnimNotifyState* AnimNotifyState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnInterrupted_4AA96CBA4011B106500E1198864653DB");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnInterrupted_4AA96CBA4011B106500E1198864653DB Parms{};

	Parms.NotifyName = NotifyName;
	Parms.AnimNotifyState = AnimNotifyState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnNotifyBegin_4AA96CBA4011B106500E1198864653DB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnNotifyBegin_4AA96CBA4011B106500E1198864653DB(class FName NotifyName, const class UAnimNotifyState* AnimNotifyState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnNotifyBegin_4AA96CBA4011B106500E1198864653DB");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnNotifyBegin_4AA96CBA4011B106500E1198864653DB Parms{};

	Parms.NotifyName = NotifyName;
	Parms.AnimNotifyState = AnimNotifyState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnNotifyEnd_4AA96CBA4011B106500E1198864653DB
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UAnimNotifyState*           AnimNotifyState                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnNotifyEnd_4AA96CBA4011B106500E1198864653DB(class FName NotifyName, const class UAnimNotifyState* AnimNotifyState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnNotifyEnd_4AA96CBA4011B106500E1198864653DB");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnNotifyEnd_4AA96CBA4011B106500E1198864653DB Parms{};

	Parms.NotifyName = NotifyName;
	Parms.AnimNotifyState = AnimNotifyState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnOwnerWeaponOverlap
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OverlapedActor                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnOwnerWeaponOverlap(class AActor* OverlapedActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnOwnerWeaponOverlap");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnOwnerWeaponOverlap Parms{};

	Parms.OverlapedActor = OverlapedActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.OnPress_2AD6593E4262562B14C300A80E7F1E35
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeWaited                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::OnPress_2AD6593E4262562B14C300A80E7F1E35(float TimeWaited)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "OnPress_2AD6593E4262562B14C300A80E7F1E35");

	Params::GA_HeavyAttack_NewBattleSystem_C_OnPress_2AD6593E4262562B14C300A80E7F1E35 Parms{};

	Parms.TimeWaited = TimeWaited;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.ResetComboStacks
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::ResetComboStacks()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "ResetComboStacks");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.SetComboInputOffset
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_HeavyAttack_NewBattleSystem_C::SetComboInputOffset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "SetComboInputOffset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.ShowComboWidget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SuccessCombo                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    SuccessStatus                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::ShowComboWidget(bool SuccessCombo, bool SuccessStatus)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "ShowComboWidget");

	Params::GA_HeavyAttack_NewBattleSystem_C_ShowComboWidget Parms{};

	Parms.SuccessCombo = SuccessCombo;
	Parms.SuccessStatus = SuccessStatus;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HeavyAttack_NewBattleSystem.GA_HeavyAttack_NewBattleSystem_C.GetDamageEffect
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UClass**                          DamageEffect                                           (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_HeavyAttack_NewBattleSystem_C::GetDamageEffect(class UClass** DamageEffect) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HeavyAttack_NewBattleSystem_C", "GetDamageEffect");

	Params::GA_HeavyAttack_NewBattleSystem_C_GetDamageEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DamageEffect != nullptr)
		*DamageEffect = Parms.DamageEffect;
}

}

