#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPC_StealthKill

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GA_NPC_BaseElimination_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_NPC_StealthKill.GA_NPC_StealthKill_C
// 0x0008 (0x0498 - 0x0490)
class UGA_NPC_StealthKill_C final : public UGA_NPC_BaseElimination_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_NPC_StealthKill_C;               // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_NPC_StealthKill(int32 EntryPoint);
	void K2_OnEndAbility(bool bWasCancelled);
	void OnNotifyTriggered(class FName Name_0, bool bIsEnded);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_NPC_StealthKill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_NPC_StealthKill_C")
	}
	static class UGA_NPC_StealthKill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_NPC_StealthKill_C>();
	}
};
DUMPER7_ASSERTS_UGA_NPC_StealthKill_C;

}

