#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_NPCFinishingOffDefeat

#include "Basic.hpp"

#include "GA_NPCFinishingOffDefeat_classes.hpp"
#include "GA_NPCFinishingOffDefeat_parameters.hpp"


namespace SDK
{

// Function GA_NPCFinishingOffDefeat.GA_NPCFinishingOffDefeat_C.ExecuteUbergraph_GA_NPCFinishingOffDefeat
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_NPCFinishingOffDefeat_C::ExecuteUbergraph_GA_NPCFinishingOffDefeat(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NPCFinishingOffDefeat_C", "ExecuteUbergraph_GA_NPCFinishingOffDefeat");

	Params::GA_NPCFinishingOffDefeat_C_ExecuteUbergraph_GA_NPCFinishingOffDefeat Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_NPCFinishingOffDefeat.GA_NPCFinishingOffDefeat_C.GetMontage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TSoftObjectPtr<class UAnimMontage>*     Montage_0                                              (Parm, OutParm, HasGetValueTypeHash)
// bool*                                   bDirectionFound                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_NPCFinishingOffDefeat_C::GetMontage(TSoftObjectPtr<class UAnimMontage>* Montage_0, bool* bDirectionFound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NPCFinishingOffDefeat_C", "GetMontage");

	Params::GA_NPCFinishingOffDefeat_C_GetMontage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Montage_0 != nullptr)
		*Montage_0 = Parms.Montage_0;

	if (bDirectionFound != nullptr)
		*bDirectionFound = Parms.bDirectionFound;
}


// Function GA_NPCFinishingOffDefeat.GA_NPCFinishingOffDefeat_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        EventData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_NPCFinishingOffDefeat_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_NPCFinishingOffDefeat_C", "K2_ActivateAbilityFromEvent");

	Params::GA_NPCFinishingOffDefeat_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}

}

