#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Parry_NewBattleSystem

#include "Basic.hpp"

#include "GA_Parry_NewBattleSystem_classes.hpp"
#include "GA_Parry_NewBattleSystem_parameters.hpp"


namespace SDK
{

// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.EventReceived_7582506C465306CF015A299F855DD736
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        Payload                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UGA_Parry_NewBattleSystem_C::EventReceived_7582506C465306CF015A299F855DD736(const struct FGameplayEventData& Payload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "EventReceived_7582506C465306CF015A299F855DD736");

	Params::GA_Parry_NewBattleSystem_C_EventReceived_7582506C465306CF015A299F855DD736 Parms{};

	Parms.Payload = std::move(Payload);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.ExecuteUbergraph_GA_Parry_NewBattleSystem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::ExecuteUbergraph_GA_Parry_NewBattleSystem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "ExecuteUbergraph_GA_Parry_NewBattleSystem");

	Params::GA_Parry_NewBattleSystem_C_ExecuteUbergraph_GA_Parry_NewBattleSystem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.Get Direction Tag
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FGameplayTagContainer*           Output                                                 (Parm, OutParm)

void UGA_Parry_NewBattleSystem_C::Get_Direction_Tag(struct FGameplayTagContainer* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "Get Direction Tag");

	Params::GA_Parry_NewBattleSystem_C_Get_Direction_Tag Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Parry_NewBattleSystem_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.K2_OnEndAbility
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "K2_OnEndAbility");

	Params::GA_Parry_NewBattleSystem_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.ManageSparks
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Spawn                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::ManageSparks(bool Spawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "ManageSparks");

	Params::GA_Parry_NewBattleSystem_C_ManageSparks Parms{};

	Parms.Spawn = Spawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnBlendOut_8E0FB62B45A89F70BD85418E26699F40
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnBlendOut_8E0FB62B45A89F70BD85418E26699F40(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnBlendOut_8E0FB62B45A89F70BD85418E26699F40");

	Params::GA_Parry_NewBattleSystem_C_OnBlendOut_8E0FB62B45A89F70BD85418E26699F40 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnBlendOut_9317A9BF4350D8D3A32AF695D12B5578
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnBlendOut_9317A9BF4350D8D3A32AF695D12B5578(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnBlendOut_9317A9BF4350D8D3A32AF695D12B5578");

	Params::GA_Parry_NewBattleSystem_C_OnBlendOut_9317A9BF4350D8D3A32AF695D12B5578 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnCompleted_8E0FB62B45A89F70BD85418E26699F40
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnCompleted_8E0FB62B45A89F70BD85418E26699F40(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnCompleted_8E0FB62B45A89F70BD85418E26699F40");

	Params::GA_Parry_NewBattleSystem_C_OnCompleted_8E0FB62B45A89F70BD85418E26699F40 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnCompleted_9317A9BF4350D8D3A32AF695D12B5578
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnCompleted_9317A9BF4350D8D3A32AF695D12B5578(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnCompleted_9317A9BF4350D8D3A32AF695D12B5578");

	Params::GA_Parry_NewBattleSystem_C_OnCompleted_9317A9BF4350D8D3A32AF695D12B5578 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnInterrupted_8E0FB62B45A89F70BD85418E26699F40
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnInterrupted_8E0FB62B45A89F70BD85418E26699F40(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnInterrupted_8E0FB62B45A89F70BD85418E26699F40");

	Params::GA_Parry_NewBattleSystem_C_OnInterrupted_8E0FB62B45A89F70BD85418E26699F40 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnInterrupted_9317A9BF4350D8D3A32AF695D12B5578
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnInterrupted_9317A9BF4350D8D3A32AF695D12B5578(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnInterrupted_9317A9BF4350D8D3A32AF695D12B5578");

	Params::GA_Parry_NewBattleSystem_C_OnInterrupted_9317A9BF4350D8D3A32AF695D12B5578 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnNotifyBegin_8E0FB62B45A89F70BD85418E26699F40
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnNotifyBegin_8E0FB62B45A89F70BD85418E26699F40(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnNotifyBegin_8E0FB62B45A89F70BD85418E26699F40");

	Params::GA_Parry_NewBattleSystem_C_OnNotifyBegin_8E0FB62B45A89F70BD85418E26699F40 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnNotifyBegin_9317A9BF4350D8D3A32AF695D12B5578
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnNotifyBegin_9317A9BF4350D8D3A32AF695D12B5578(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnNotifyBegin_9317A9BF4350D8D3A32AF695D12B5578");

	Params::GA_Parry_NewBattleSystem_C_OnNotifyBegin_9317A9BF4350D8D3A32AF695D12B5578 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnNotifyEnd_8E0FB62B45A89F70BD85418E26699F40
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnNotifyEnd_8E0FB62B45A89F70BD85418E26699F40(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnNotifyEnd_8E0FB62B45A89F70BD85418E26699F40");

	Params::GA_Parry_NewBattleSystem_C_OnNotifyEnd_8E0FB62B45A89F70BD85418E26699F40 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.OnNotifyEnd_9317A9BF4350D8D3A32AF695D12B5578
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             NotifyName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::OnNotifyEnd_9317A9BF4350D8D3A32AF695D12B5578(class FName NotifyName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "OnNotifyEnd_9317A9BF4350D8D3A32AF695D12B5578");

	Params::GA_Parry_NewBattleSystem_C_OnNotifyEnd_9317A9BF4350D8D3A32AF695D12B5578 Parms{};

	Parms.NotifyName = NotifyName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.ParryWindowEnd
// (BlueprintCallable, BlueprintEvent)

void UGA_Parry_NewBattleSystem_C::ParryWindowEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "ParryWindowEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.ParryWindowStart
// (BlueprintCallable, BlueprintEvent)

void UGA_Parry_NewBattleSystem_C::ParryWindowStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "ParryWindowStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Parry_NewBattleSystem.GA_Parry_NewBattleSystem_C.RotateAvatarActorToAttacker
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Enemy                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Attacker_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_Parry_NewBattleSystem_C::RotateAvatarActorToAttacker(class AActor* Enemy, class AActor* Attacker_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Parry_NewBattleSystem_C", "RotateAvatarActorToAttacker");

	Params::GA_Parry_NewBattleSystem_C_RotateAvatarActorToAttacker Parms{};

	Parms.Enemy = Enemy;
	Parms.Attacker_0 = Attacker_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

