#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_MarsAmulet

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_MarsAmulet.GE_MarsAmulet_C
// 0x0000 (0x0A70 - 0x0A70)
class UGE_MarsAmulet_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_MarsAmulet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_MarsAmulet_C")
	}
	static class UGE_MarsAmulet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_MarsAmulet_C>();
	}
};
DUMPER7_ASSERTS_UGE_MarsAmulet_C;

}

