#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeAttackDamageMagnitude_MM

#include "Basic.hpp"

#include "MeleeAttackDamageMagnitude_MM_classes.hpp"
#include "MeleeAttackDamageMagnitude_MM_parameters.hpp"


namespace SDK
{

// Function MeleeAttackDamageMagnitude_MM.MeleeAttackDamageMagnitude_MM_C.CalculateBaseMagnitude
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FGameplayEffectSpec&       Spec                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UMeleeAttackDamageMagnitude_MM_C::CalculateBaseMagnitude(const struct FGameplayEffectSpec& Spec) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MeleeAttackDamageMagnitude_MM_C", "CalculateBaseMagnitude");

	Params::MeleeAttackDamageMagnitude_MM_C_CalculateBaseMagnitude Parms{};

	Parms.Spec = std::move(Spec);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

