#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NF_1Zone

#include "Basic.hpp"

#include "NavigationSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NF_1Zone.NF_1Zone_C
// 0x0000 (0x0048 - 0x0048)
class UNF_1Zone_C final : public UNavigationQueryFilter
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NF_1Zone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NF_1Zone_C")
	}
	static class UNF_1Zone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNF_1Zone_C>();
	}
};
DUMPER7_ASSERTS_UNF_1Zone_C;

}

