#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: O_InteractCondition_FractionAttitude

#include "Basic.hpp"

#include "O_InteractCondition_FractionAttitude_classes.hpp"
#include "O_InteractCondition_FractionAttitude_parameters.hpp"


namespace SDK
{

// Function O_InteractCondition_FractionAttitude.O_InteractCondition_FractionAttitude_C.EndCondition
// (Event, Public, BlueprintEvent)

void UO_InteractCondition_FractionAttitude_C::EndCondition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("O_InteractCondition_FractionAttitude_C", "EndCondition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function O_InteractCondition_FractionAttitude.O_InteractCondition_FractionAttitude_C.ExecuteUbergraph_O_InteractCondition_FractionAttitude
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UO_InteractCondition_FractionAttitude_C::ExecuteUbergraph_O_InteractCondition_FractionAttitude(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("O_InteractCondition_FractionAttitude_C", "ExecuteUbergraph_O_InteractCondition_FractionAttitude");

	Params::O_InteractCondition_FractionAttitude_C_ExecuteUbergraph_O_InteractCondition_FractionAttitude Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function O_InteractCondition_FractionAttitude.O_InteractCondition_FractionAttitude_C.StartCondition
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UO_InteractCondition_FractionAttitude_C::StartCondition(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("O_InteractCondition_FractionAttitude_C", "StartCondition");

	Params::O_InteractCondition_FractionAttitude_C_StartCondition Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

