#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QA_PlaySubtitledSound

#include "Basic.hpp"

#include "QA_PlaySubtitledSound_classes.hpp"
#include "QA_PlaySubtitledSound_parameters.hpp"


namespace SDK
{

// Function QA_PlaySubtitledSound.QA_PlaySubtitledSound_C.ExecuteUbergraph_QA_PlaySubtitledSound
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQA_PlaySubtitledSound_C::ExecuteUbergraph_QA_PlaySubtitledSound(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_PlaySubtitledSound_C", "ExecuteUbergraph_QA_PlaySubtitledSound");

	Params::QA_PlaySubtitledSound_C_ExecuteUbergraph_QA_PlaySubtitledSound Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QA_PlaySubtitledSound.QA_PlaySubtitledSound_C.RunAction_K2
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UQuestStep*                       FromQuestStep                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UQA_PlaySubtitledSound_C::RunAction_K2(class UQuestStep* FromQuestStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_PlaySubtitledSound_C", "RunAction_K2");

	Params::QA_PlaySubtitledSound_C_RunAction_K2 Parms{};

	Parms.FromQuestStep = FromQuestStep;

	UObject::ProcessEvent(Func, &Parms);
}

}

