#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QA_StartIndependentFootstep

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FlexibleQuestsRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QA_StartIndependentFootstep.QA_StartIndependentFootstep_C
// 0x0030 (0x0060 - 0x0030)
class UQA_StartIndependentFootstep_C final : public UQuestStepAction
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TSoftObjectPtr<class AA_EvidenceFootprints_C> Footprints;                                        // 0x0038(0x0028)(Edit, BlueprintVisible, SaveGame, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QA_StartIndependentFootstep(int32 EntryPoint);
	void OnLoaded_5DB3FB33457ACD484A2D8692E217CC18(class UObject* Loaded);
	void RunAction_K2(class UQuestStep* FromQuestStep);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QA_StartIndependentFootstep_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QA_StartIndependentFootstep_C")
	}
	static class UQA_StartIndependentFootstep_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQA_StartIndependentFootstep_C>();
	}
};
DUMPER7_ASSERTS_UQA_StartIndependentFootstep_C;

}

