#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QA_StartIndependentFootstep

#include "Basic.hpp"

#include "QA_StartIndependentFootstep_classes.hpp"
#include "QA_StartIndependentFootstep_parameters.hpp"


namespace SDK
{

// Function QA_StartIndependentFootstep.QA_StartIndependentFootstep_C.ExecuteUbergraph_QA_StartIndependentFootstep
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQA_StartIndependentFootstep_C::ExecuteUbergraph_QA_StartIndependentFootstep(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_StartIndependentFootstep_C", "ExecuteUbergraph_QA_StartIndependentFootstep");

	Params::QA_StartIndependentFootstep_C_ExecuteUbergraph_QA_StartIndependentFootstep Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QA_StartIndependentFootstep.QA_StartIndependentFootstep_C.OnLoaded_5DB3FB33457ACD484A2D8692E217CC18
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UQA_StartIndependentFootstep_C::OnLoaded_5DB3FB33457ACD484A2D8692E217CC18(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_StartIndependentFootstep_C", "OnLoaded_5DB3FB33457ACD484A2D8692E217CC18");

	Params::QA_StartIndependentFootstep_C_OnLoaded_5DB3FB33457ACD484A2D8692E217CC18 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QA_StartIndependentFootstep.QA_StartIndependentFootstep_C.RunAction_K2
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UQuestStep*                       FromQuestStep                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UQA_StartIndependentFootstep_C::RunAction_K2(class UQuestStep* FromQuestStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_StartIndependentFootstep_C", "RunAction_K2");

	Params::QA_StartIndependentFootstep_C_RunAction_K2 Parms{};

	Parms.FromQuestStep = FromQuestStep;

	UObject::ProcessEvent(Func, &Parms);
}

}

