#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QA_TeleportObject

#include "Basic.hpp"

#include "QA_TeleportObject_classes.hpp"
#include "QA_TeleportObject_parameters.hpp"


namespace SDK
{

// Function QA_TeleportObject.QA_TeleportObject_C.ExecuteUbergraph_QA_TeleportObject
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQA_TeleportObject_C::ExecuteUbergraph_QA_TeleportObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_TeleportObject_C", "ExecuteUbergraph_QA_TeleportObject");

	Params::QA_TeleportObject_C_ExecuteUbergraph_QA_TeleportObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QA_TeleportObject.QA_TeleportObject_C.RunAction_K2
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UQuestStep*                       FromQuestStep                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UQA_TeleportObject_C::RunAction_K2(class UQuestStep* FromQuestStep)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QA_TeleportObject_C", "RunAction_K2");

	Params::QA_TeleportObject_C_RunAction_K2 Parms{};

	Parms.FromQuestStep = FromQuestStep;

	UObject::ProcessEvent(Func, &Parms);
}

}

