#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QC_PlayAndWaitCutscene

#include "Basic.hpp"

#include "QC_PlayAndWaitCutscene_classes.hpp"
#include "QC_PlayAndWaitCutscene_parameters.hpp"


namespace SDK
{

// Function QC_PlayAndWaitCutscene.QC_PlayAndWaitCutscene_C.ExecuteUbergraph_QC_PlayAndWaitCutscene
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UQC_PlayAndWaitCutscene_C::ExecuteUbergraph_QC_PlayAndWaitCutscene(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QC_PlayAndWaitCutscene_C", "ExecuteUbergraph_QC_PlayAndWaitCutscene");

	Params::QC_PlayAndWaitCutscene_C_ExecuteUbergraph_QC_PlayAndWaitCutscene Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QC_PlayAndWaitCutscene.QC_PlayAndWaitCutscene_C.OnCutscenePlayed_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULevelSequence*                   Cutscene_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UQC_PlayAndWaitCutscene_C::OnCutscenePlayed_Event(class ULevelSequence* Cutscene_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QC_PlayAndWaitCutscene_C", "OnCutscenePlayed_Event");

	Params::QC_PlayAndWaitCutscene_C_OnCutscenePlayed_Event Parms{};

	Parms.Cutscene_0 = Cutscene_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function QC_PlayAndWaitCutscene.QC_PlayAndWaitCutscene_C.StartCondition_K2
// (Event, Protected, BlueprintEvent)

void UQC_PlayAndWaitCutscene_C::StartCondition_K2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("QC_PlayAndWaitCutscene_C", "StartCondition_K2");

	UObject::ProcessEvent(Func, nullptr);
}

}

