#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QC_SplineFinished

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FlexibleQuestsRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QC_SplineFinished.QC_SplineFinished_C
// 0x0030 (0x0088 - 0x0058)
class UQC_SplineFinished_C final : public UQuestStepCondition
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0058(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TSoftObjectPtr<class ANPC_CH_C>               NPC;                                               // 0x0060(0x0028)(Edit, BlueprintVisible, SaveGame, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QC_SplineFinished(int32 EntryPoint);
	void HandleSplineFinish();
	void SetConditionState(class AAIController* OwnerController, class ASplineActor* CurrentSplineActor);
	void StartCondition_K2();
	void TargetsUpdate();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QC_SplineFinished_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QC_SplineFinished_C")
	}
	static class UQC_SplineFinished_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQC_SplineFinished_C>();
	}
};
DUMPER7_ASSERTS_UQC_SplineFinished_C;

}

