#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QC_WavesCleared

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FlexibleQuestsRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QC_WavesCleared.QC_WavesCleared_C
// 0x0040 (0x0098 - 0x0058)
class UQC_WavesCleared_C final : public UQuestStepCondition
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0058(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TSoftObjectPtr<class ABP_EnemyWaves_C>        Waves;                                             // 0x0060(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame, HasGetValueTypeHash)
	class AActor*                                 AddTarget;                                         // 0x0088(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 RemoveTarget;                                      // 0x0090(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AmbushWavesCleared();
	void D_OnWaveCharacterSpawned_Event(class ANPC_CH_C* NewCharacter);
	void EndCondition_K2();
	void ExecuteUbergraph_QC_WavesCleared(int32 EntryPoint);
	void OnLoaded();
	void OnTagChanged(class UAbilitySystemComponent* ASC, const struct FGameplayTag& UpdatedTag, bool Exists);
	void StartCondition_K2();
	void TargetsUpdate();

	class FText GetConditionText() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QC_WavesCleared_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QC_WavesCleared_C")
	}
	static class UQC_WavesCleared_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQC_WavesCleared_C>();
	}
};
DUMPER7_ASSERTS_UQC_WavesCleared_C;

}

