#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QC_WaitNPCTag

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FlexibleQuestsRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass QC_WaitNPCTag.QC_WaitNPCTag_C
// 0x0038 (0x0090 - 0x0058)
class UQC_WaitNPCTag_C : public UQuestStepCondition
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0058(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           Tag;                                               // 0x0060(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class ANPC_CH_NewBattleSystem_C> NPC;                                             // 0x0068(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance, SaveGame, HasGetValueTypeHash)

public:
	void EndCondition_K2();
	void ExecuteUbergraph_QC_WaitNPCTag(int32 EntryPoint);
	void OnLoaded();
	void OnTagChanged_Event(const struct FGameplayTag& UpdatedTag, bool Exists);
	void PostLoadDelegate_Event(const bool SaveLoadResult);
	void StartCondition_K2();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QC_WaitNPCTag_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QC_WaitNPCTag_C")
	}
	static class UQC_WaitNPCTag_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQC_WaitNPCTag_C>();
	}
};
DUMPER7_ASSERTS_UQC_WaitNPCTag_C;

}

