#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QTE_ALI

#include "Basic.hpp"

#include "QTE_ALI_classes.hpp"
#include "QTE_ALI_parameters.hpp"


namespace SDK
{

// Function QTE_ALI.QTE_ALI_C.QTE
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       QTE_0                                                  (Parm, OutParm, NoDestructor)

void IQTE_ALI_C::QTE(const struct FPoseLink& InPose, struct FPoseLink* QTE_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("QTE_ALI_C", "QTE");

	Params::QTE_ALI_C_QTE Parms{};

	Parms.InPose = std::move(InPose);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (QTE_0 != nullptr)
		*QTE_0 = std::move(Parms.QTE_0);
}

}

