#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RangeAttackDamageMagnitude_MM

#include "Basic.hpp"

#include "RangeAttackDamageMagnitude_MM_classes.hpp"
#include "RangeAttackDamageMagnitude_MM_parameters.hpp"


namespace SDK
{

// Function RangeAttackDamageMagnitude_MM.RangeAttackDamageMagnitude_MM_C.CalculateBaseMagnitude
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FGameplayEffectSpec&       Spec                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float URangeAttackDamageMagnitude_MM_C::CalculateBaseMagnitude(const struct FGameplayEffectSpec& Spec) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RangeAttackDamageMagnitude_MM_C", "CalculateBaseMagnitude");

	Params::RangeAttackDamageMagnitude_MM_C_CalculateBaseMagnitude Parms{};

	Parms.Spec = std::move(Spec);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

