#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_HitMontagesByTag

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Smuta_structs.hpp"


namespace SDK
{

// UserDefinedStruct S_HitMontagesByTag.S_HitMontagesByTag
// 0x0050 (0x0050 - 0x0000)
struct FS_HitMontagesByTag final
{
public:
	TMap<struct FGameplayTag, struct FHitActionMontages> Montages_6_F651E91547E9E0B59C6409915941932F; // 0x0000(0x0050)(Edit, BlueprintVisible)
};
DUMPER7_ASSERTS_FS_HitMontagesByTag;

}

