#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Codex_TutorialContent

#include "Basic.hpp"

#include "UI_Codex_TutorialContent_classes.hpp"
#include "UI_Codex_TutorialContent_parameters.hpp"


namespace SDK
{

// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ClearStates
// (Private, BlueprintCallable, BlueprintEvent)

void UUI_Codex_TutorialContent_C::ClearStates()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ClearStates");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ExecuteUbergraph_UI_Codex_TutorialContent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ExecuteUbergraph_UI_Codex_TutorialContent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ExecuteUbergraph_UI_Codex_TutorialContent");

	Params::UI_Codex_TutorialContent_C_ExecuteUbergraph_UI_Codex_TutorialContent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.OnActivated
// (BlueprintCallable, BlueprintEvent)

void UUI_Codex_TutorialContent_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.OnDeactivated
// (BlueprintCallable, BlueprintEvent)

void UUI_Codex_TutorialContent_C::OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.OnVideoEndReached
// (BlueprintCallable, BlueprintEvent)

void UUI_Codex_TutorialContent_C::OnVideoEndReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "OnVideoEndReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.OnVideoStarted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    OpenUrl                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::OnVideoStarted(const class FString& OpenUrl)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "OnVideoStarted");

	Params::UI_Codex_TutorialContent_C_OnVideoStarted Parms{};

	Parms.OpenUrl = std::move(OpenUrl);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "PreConstruct");

	Params::UI_Codex_TutorialContent_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ShowBasePopupContent
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTutorialBasePopupHintContent*    Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ShowBasePopupContent(class UTutorialBasePopupHintContent* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ShowBasePopupContent");

	Params::UI_Codex_TutorialContent_C_ShowBasePopupContent Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ShowContent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTutorialBaseContent*             Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ShowContent(class UTutorialBaseContent* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ShowContent");

	Params::UI_Codex_TutorialContent_C_ShowContent Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ShowImageContent
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTutorialPopupHintImageContent*   Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ShowImageContent(class UTutorialPopupHintImageContent* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ShowImageContent");

	Params::UI_Codex_TutorialContent_C_ShowImageContent Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ShowTextContent
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTutorialNonBlockingHintContent*  Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ShowTextContent(class UTutorialNonBlockingHintContent* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ShowTextContent");

	Params::UI_Codex_TutorialContent_C_ShowTextContent Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Codex_TutorialContent.UI_Codex_TutorialContent_C.ShowVideoContent
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTutorialPopupHintVideoContent*   Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_Codex_TutorialContent_C::ShowVideoContent(class UTutorialPopupHintVideoContent* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Codex_TutorialContent_C", "ShowVideoContent");

	Params::UI_Codex_TutorialContent_C_ShowVideoContent Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}

}

