#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_EquipmentSlots_Base

#include "Basic.hpp"

#include "UI_EquipmentSlots_Base_classes.hpp"
#include "UI_EquipmentSlots_Base_parameters.hpp"


namespace SDK
{

// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.GetDesiredFocusTarget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget**                         Target                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_EquipmentSlots_Base_C::GetDesiredFocusTarget(class UWidget** Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "GetDesiredFocusTarget");

	Params::UI_EquipmentSlots_Base_C_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Target != nullptr)
		*Target = Parms.Target;
}


// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.InitEqupmentSlots
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAppearanceItem*                  Appearance_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUI_EquipmentSlots_Base_C::InitEqupmentSlots(class UAppearanceItem* Appearance_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "InitEqupmentSlots");

	Params::UI_EquipmentSlots_Base_C_InitEqupmentSlots Parms{};

	Parms.Appearance_0 = Appearance_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.SetSlotSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SlotIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_EquipmentSlots_Base_C::SetSlotSelected(int32 SlotIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "SetSlotSelected");

	Params::UI_EquipmentSlots_Base_C_SetSlotSelected Parms{};

	Parms.SlotIndex = SlotIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.ShowIcon
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           Icon                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Show                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_EquipmentSlots_Base_C::ShowIcon(class UImage* Icon, bool Show)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "ShowIcon");

	Params::UI_EquipmentSlots_Base_C_ShowIcon Parms{};

	Parms.Icon = Icon;
	Parms.Show = Show;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.SlotDoubleClicked
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_EquipmentSlots_Base_C::SlotDoubleClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "SlotDoubleClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_EquipmentSlots_Base.UI_EquipmentSlots_Base_C.UpdateDescription
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_EquipmentSlot_Base_C*         Slot_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_EquipmentSlots_Base_C::UpdateDescription(class UUI_EquipmentSlot_Base_C* Slot_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_EquipmentSlots_Base_C", "UpdateDescription");

	Params::UI_EquipmentSlots_Base_C_UpdateDescription Parms{};

	Parms.Slot_0 = Slot_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

