#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_FightMassage

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_FightMassage.UI_FightMassage_C
// 0x0010 (0x02D0 - 0x02C0)
class UUI_FightMassage_C final : public UUserWidget
{
public:
	class UImage*                                 Image_148;                                         // 0x02C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       InteractText;                                      // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_FightMassage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_FightMassage_C")
	}
	static class UUI_FightMassage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_FightMassage_C>();
	}
};
DUMPER7_ASSERTS_UUI_FightMassage_C;

}

