#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_fade

#include "Basic.hpp"

#include "UI_fade_classes.hpp"
#include "UI_fade_parameters.hpp"


namespace SDK
{

// Function UI_fade.UI_fade_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_fade_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_fade_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_fade.UI_fade_C.ExecuteUbergraph_UI_fade
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_fade_C::ExecuteUbergraph_UI_fade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_fade_C", "ExecuteUbergraph_UI_fade");

	Params::UI_fade_C_ExecuteUbergraph_UI_fade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_fade.UI_fade_C.FadeOutEvent
// (BlueprintCallable, BlueprintEvent)

void UUI_fade_C::FadeOutEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_fade_C", "FadeOutEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_fade.UI_fade_C.RestartFadeOutTimer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  NewShowTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_fade_C::RestartFadeOutTimer(double NewShowTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_fade_C", "RestartFadeOutTimer");

	Params::UI_fade_C_RestartFadeOutTimer Parms{};

	Parms.NewShowTime = NewShowTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

