#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Fractions

#include "Basic.hpp"

#include "UI_Menu_Fractions_classes.hpp"
#include "UI_Menu_Fractions_parameters.hpp"


namespace SDK
{

// Function UI_Menu_Fractions.UI_Menu_Fractions_C.BndEvt__UI_Menu_Fractions_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::BndEvt__UI_Menu_Fractions_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "BndEvt__UI_Menu_Fractions_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::UI_Menu_Fractions_C_BndEvt__UI_Menu_Fractions_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UUI_Menu_Fractions_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Menu_Fractions_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Menu_Fractions_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.ExecuteUbergraph_UI_Menu_Fractions
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::ExecuteUbergraph_UI_Menu_Fractions(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "ExecuteUbergraph_UI_Menu_Fractions");

	Params::UI_Menu_Fractions_C_ExecuteUbergraph_UI_Menu_Fractions Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.OnFractionSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool                                    Selected                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::OnFractionSelected(class UCommonButtonBase* Button, bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "OnFractionSelected");

	Params::UI_Menu_Fractions_C_OnFractionSelected Parms{};

	Parms.Button = Button;
	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "PreConstruct");

	Params::UI_Menu_Fractions_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.Update Fraction Members
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FFractionData&             FractionData                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FFractionProgressionInfo&  FarctionProgressionInfo                                (BlueprintVisible, BlueprintReadOnly, Parm)
// ESmutaDLCFraction                       FractionId                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::Update_Fraction_Members(const struct FFractionData& FractionData, const struct FFractionProgressionInfo& FarctionProgressionInfo, ESmutaDLCFraction FractionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "Update Fraction Members");

	Params::UI_Menu_Fractions_C_Update_Fraction_Members Parms{};

	Parms.FractionData = std::move(FractionData);
	Parms.FarctionProgressionInfo = std::move(FarctionProgressionInfo);
	Parms.FractionId = FractionId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.UpdateOnFractionSelected
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                SelectedButton                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Fractions_C::UpdateOnFractionSelected(class UCommonButtonBase* SelectedButton, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "UpdateOnFractionSelected");

	Params::UI_Menu_Fractions_C_UpdateOnFractionSelected Parms{};

	Parms.SelectedButton = SelectedButton;

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function UI_Menu_Fractions.UI_Menu_Fractions_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUI_Menu_Fractions_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Fractions_C", "BP_GetDesiredFocusTarget");

	Params::UI_Menu_Fractions_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

