#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Menu_Equipment

#include "Basic.hpp"

#include "UI_Menu_Equipment_classes.hpp"
#include "UI_Menu_Equipment_parameters.hpp"


namespace SDK
{

// Function UI_Menu_Equipment.UI_Menu_Equipment_C.BndEvt__UI_Menu_Equipment_BTN_Accept_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Equipment_C::BndEvt__UI_Menu_Equipment_BTN_Accept_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "BndEvt__UI_Menu_Equipment_BTN_Accept_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::UI_Menu_Equipment_C_BndEvt__UI_Menu_Equipment_BTN_Accept_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.BndEvt__UI_Menu_Equipment_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Equipment_C::BndEvt__UI_Menu_Equipment_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "BndEvt__UI_Menu_Equipment_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature");

	Params::UI_Menu_Equipment_C_BndEvt__UI_Menu_Equipment_BTN_Back_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.BndEvt__UI_Menu_Equipment_UI_EquipmentSlots_Shish_K2Node_ComponentBoundEvent_2_OnSlotDoubleClicked__DelegateSignature
// (BlueprintEvent)

void UUI_Menu_Equipment_C::BndEvt__UI_Menu_Equipment_UI_EquipmentSlots_Shish_K2Node_ComponentBoundEvent_2_OnSlotDoubleClicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "BndEvt__UI_Menu_Equipment_UI_EquipmentSlots_Shish_K2Node_ComponentBoundEvent_2_OnSlotDoubleClicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UUI_Menu_Equipment_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Menu_Equipment_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.ExecuteUbergraph_UI_Menu_Equipment
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Equipment_C::ExecuteUbergraph_UI_Menu_Equipment(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "ExecuteUbergraph_UI_Menu_Equipment");

	Params::UI_Menu_Equipment_C_ExecuteUbergraph_UI_Menu_Equipment Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.Get_Header_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UUI_Menu_Equipment_C::Get_Header_Visibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "Get_Header_Visibility");

	Params::UI_Menu_Equipment_C_Get_Header_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.GetSelectedSlot
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32*                                  Slot_0                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Equipment_C::GetSelectedSlot(int32* Slot_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "GetSelectedSlot");

	Params::UI_Menu_Equipment_C_GetSelectedSlot Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Slot_0 != nullptr)
		*Slot_0 = Parms.Slot_0;
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.Init Equipment
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Menu_Equipment_C::Init_Equipment(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "Init Equipment");

	Params::UI_Menu_Equipment_C_Init_Equipment Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.InitBoyar
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Equipment_C::InitBoyar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "InitBoyar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.InitMercenary
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Equipment_C::InitMercenary()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "InitMercenary");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.InitShish
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Equipment_C::InitShish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "InitShish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.InitStreletc
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Menu_Equipment_C::InitStreletc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "InitStreletc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Menu_Equipment.UI_Menu_Equipment_C.BP_GetDesiredFocusTarget
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UUI_Menu_Equipment_C::BP_GetDesiredFocusTarget() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Menu_Equipment_C", "BP_GetDesiredFocusTarget");

	Params::UI_Menu_Equipment_C_BP_GetDesiredFocusTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

