#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_NotifyCodex

#include "Basic.hpp"

#include "UI_NotifyCodex_classes.hpp"
#include "UI_NotifyCodex_parameters.hpp"


namespace SDK
{

// Function UI_NotifyCodex.UI_NotifyCodex_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_NotifyCodex_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.CustomEvent_0
// (BlueprintCallable, BlueprintEvent)

void UUI_NotifyCodex_C::CustomEvent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "CustomEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.ExecuteUbergraph_UI_NotifyCodex
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_NotifyCodex_C::ExecuteUbergraph_UI_NotifyCodex(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "ExecuteUbergraph_UI_NotifyCodex");

	Params::UI_NotifyCodex_C_ExecuteUbergraph_UI_NotifyCodex Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.FindNameByID
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText*                            Name_0                                                 (Parm, OutParm)

void UUI_NotifyCodex_C::FindNameByID(class FText* Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "FindNameByID");

	Params::UI_NotifyCodex_C_FindNameByID Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Name_0 != nullptr)
		*Name_0 = std::move(Parms.Name_0);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.InitCodexData
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_NotifyCodex_C::InitCodexData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "InitCodexData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_NotifyCodex_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.PlayNotifySound
// (BlueprintCallable, BlueprintEvent)

void UUI_NotifyCodex_C::PlayNotifySound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "PlayNotifySound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_NotifyCodex.UI_NotifyCodex_C.RemoveNotify
// (BlueprintCallable, BlueprintEvent)

void UUI_NotifyCodex_C::RemoveNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_NotifyCodex_C", "RemoveNotify");

	UObject::ProcessEvent(Func, nullptr);
}

}

