#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PopUp_KeyAlreadyBound

#include "Basic.hpp"

#include "InputCore_structs.hpp"
#include "WB_MenuPopup_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_PopUp_KeyAlreadyBound.UI_PopUp_KeyAlreadyBound_C
// 0x0028 (0x04D8 - 0x04B0)
class UUI_PopUp_KeyAlreadyBound_C final : public UWB_MenuPopup_Base_C
{
public:
	TMulticastInlineDelegate<void(bool IsPlayerAgree, const struct FKey& Key)> OnPlayerOption;       // 0x04B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FKey                                   New_Key;                                           // 0x04C0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void InitMessage(const class FText& NewAction, const class FText& OldAction, const struct FKey& NewKey);
	void OnCancel();
	void OnConfirm();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UI_PopUp_KeyAlreadyBound_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UI_PopUp_KeyAlreadyBound_C")
	}
	static class UUI_PopUp_KeyAlreadyBound_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_PopUp_KeyAlreadyBound_C>();
	}
};
DUMPER7_ASSERTS_UUI_PopUp_KeyAlreadyBound_C;

}

