#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UW_FPSCounter

#include "Basic.hpp"

#include "UW_FPSCounter_classes.hpp"
#include "UW_FPSCounter_parameters.hpp"


namespace SDK
{

// Function UW_FPSCounter.UW_FPSCounter_C.Benchmark
// (Exec, Public, BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::Benchmark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Benchmark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.CustomEvent_OnCameraCut
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCameraComponent*                 CameraComponent                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUW_FPSCounter_C::CustomEvent_OnCameraCut(class UCameraComponent* CameraComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "CustomEvent_OnCameraCut");

	Params::UW_FPSCounter_C_CustomEvent_OnCameraCut Parms{};

	Parms.CameraComponent = CameraComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UW_FPSCounter.UW_FPSCounter_C.ExecuteUbergraph_UW_FPSCounter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUW_FPSCounter_C::ExecuteUbergraph_UW_FPSCounter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "ExecuteUbergraph_UW_FPSCounter");

	Params::UW_FPSCounter_C_ExecuteUbergraph_UW_FPSCounter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UW_FPSCounter.UW_FPSCounter_C.Get_Raw_Value_Text
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UUW_FPSCounter_C::Get_Raw_Value_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Get_Raw_Value_Text");

	Params::UW_FPSCounter_C_Get_Raw_Value_Text Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UW_FPSCounter.UW_FPSCounter_C.GetTimeStamp
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UUW_FPSCounter_C::GetTimeStamp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "GetTimeStamp");

	Params::UW_FPSCounter_C_GetTimeStamp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function UW_FPSCounter.UW_FPSCounter_C.Hide
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.Log
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::Log()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Log");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.LogResult
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::LogResult()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "LogResult");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUW_FPSCounter_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.OnLoaded_B3599DCE4DC4FD1318240EAA70FA1F78
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUW_FPSCounter_C::OnLoaded_B3599DCE4DC4FD1318240EAA70FA1F78(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "OnLoaded_B3599DCE4DC4FD1318240EAA70FA1F78");

	Params::UW_FPSCounter_C_OnLoaded_B3599DCE4DC4FD1318240EAA70FA1F78 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UW_FPSCounter.UW_FPSCounter_C.Reset
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ResetAggregated                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUW_FPSCounter_C::Reset(bool ResetAggregated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Reset");

	Params::UW_FPSCounter_C_Reset Parms{};

	Parms.ResetAggregated = ResetAggregated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UW_FPSCounter.UW_FPSCounter_C.SetSystemSpecs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::SetSystemSpecs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "SetSystemSpecs");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.Show
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::Show()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Show");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.StartFPSBenchmark
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::StartFPSBenchmark()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "StartFPSBenchmark");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.StartUpdate
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::StartUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "StartUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.StopUpdate
// (BlueprintCallable, BlueprintEvent)

void UUW_FPSCounter_C::StopUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "StopUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UW_FPSCounter.UW_FPSCounter_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUW_FPSCounter_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UW_FPSCounter_C", "Tick");

	Params::UW_FPSCounter_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

