#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WB_TagEventComboWidget

#include "Basic.hpp"

#include "WB_TagEventComboWidget_classes.hpp"
#include "WB_TagEventComboWidget_parameters.hpp"


namespace SDK
{

// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.CloseHint
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::CloseHint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "CloseHint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.ExecuteUbergraph_WB_TagEventComboWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_TagEventComboWidget_C::ExecuteUbergraph_WB_TagEventComboWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "ExecuteUbergraph_WB_TagEventComboWidget");

	Params::WB_TagEventComboWidget_C_ExecuteUbergraph_WB_TagEventComboWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.FillOut
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::FillOut()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "FillOut");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.Get Curent Combo Item
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_TagComboItem_C**              AsWB_Tag_Combo_Item                                    (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_TagEventComboWidget_C::Get_Curent_Combo_Item(class UWB_TagComboItem_C** AsWB_Tag_Combo_Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "Get Curent Combo Item");

	Params::WB_TagEventComboWidget_C_Get_Curent_Combo_Item Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsWB_Tag_Combo_Item != nullptr)
		*AsWB_Tag_Combo_Item = Parms.AsWB_Tag_Combo_Item;
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.Get Next Combo Item
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWB_TagComboItem_C**              AsWB_Tag_Combo_Item                                    (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWB_TagEventComboWidget_C::Get_Next_Combo_Item(class UWB_TagComboItem_C** AsWB_Tag_Combo_Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "Get Next Combo Item");

	Params::WB_TagEventComboWidget_C_Get_Next_Combo_Item Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsWB_Tag_Combo_Item != nullptr)
		*AsWB_Tag_Combo_Item = Parms.AsWB_Tag_Combo_Item;
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.GetHintTextContainer
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class URichTextBlock*                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class URichTextBlock* UWB_TagEventComboWidget_C::GetHintTextContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "GetHintTextContainer");

	Params::WB_TagEventComboWidget_C_GetHintTextContainer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnAnimFinished
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Object                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FFieldNotificationId&      Field                                                  (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWB_TagEventComboWidget_C::OnAnimFinished(class UObject* Object, const struct FFieldNotificationId& Field)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnAnimFinished");

	Params::WB_TagEventComboWidget_C_OnAnimFinished Parms{};

	Parms.Object = Object;
	Parms.Field = std::move(Field);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnCleanup
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnCleanup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnCleanup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnComboFailed
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnComboFailed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnComboFailed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnComboFinished
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnComboFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnComboFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnComboRestarted
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnComboRestarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnComboRestarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnComboSuccess
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnComboSuccess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnComboSuccess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.OnProgressCombo
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::OnProgressCombo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "OnProgressCombo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.RefreshWidget
// (Event, Protected, BlueprintEvent)

void UWB_TagEventComboWidget_C::RefreshWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "RefreshWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.ResetAllItems
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_TagEventComboWidget_C::ResetAllItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "ResetAllItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.SetWidgetVisuals
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWB_TagEventComboWidget_C::SetWidgetVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "SetWidgetVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WB_TagEventComboWidget.WB_TagEventComboWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWB_TagEventComboWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WB_TagEventComboWidget_C", "Tick");

	Params::WB_TagEventComboWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

