#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: YnnkVoiceLipsync

#include "Basic.hpp"

#include "YnnkVoiceLipsync_structs.hpp"


namespace SDK::Params
{

// Function YnnkVoiceLipsync.AsyncRecognizer.AsyncRecognizeAudio
// 0x0038 (0x0038 - 0x0000)
struct AsyncRecognizer_AsyncRecognizeAudio final
{
public:
	int32                                         ID;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint8>                                 InRawPCMData;                                      // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	uint32                                        InSampleRate;                                      // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Duration;                                          // 0x0020(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 ID, const TArray<struct FSingeWordData>& Data)> InCallbackEvent;            // 0x0024(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AsyncRecognizer_AsyncRecognizeAudio;

// Function YnnkVoiceLipsync.AsyncRecognizer.AsyncRecognizeAudioAndGenerateAsset
// 0x0038 (0x0038 - 0x0000)
struct AsyncRecognizer_AsyncRecognizeAudioAndGenerateAsset final
{
public:
	TArray<uint8>                                 InRawPCMData;                                      // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	uint32                                        InSampleRate;                                      // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Duration;                                          // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundWave*                             OutSoundWave;                                      // 0x0020(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UYnnkVoiceLipsyncData* VoiceLipsyncData, bool bResult, const class FString& Subtitles)> InCallbackEvent; // 0x0028(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AsyncRecognizer_AsyncRecognizeAudioAndGenerateAsset;

// Function YnnkVoiceLipsync.AsyncRecognizer.AsyncRecognizeQueue
// 0x0010 (0x0010 - 0x0000)
struct AsyncRecognizer_AsyncRecognizeQueue final
{
public:
	int32                                         ID;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UYnnkVoiceLipsyncData*                  Target;                                            // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AsyncRecognizer_AsyncRecognizeQueue;

// Function YnnkVoiceLipsync.AsyncRecognizer.NextFromQueue_Internal
// 0x0008 (0x0008 - 0x0000)
struct AsyncRecognizer_NextFromQueue_Internal final
{
public:
	int32                                         CompletedIndex;                                    // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResult;                                           // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AsyncRecognizer_NextFromQueue_Internal;

// Function YnnkVoiceLipsync.AsyncRecognizer.RecognizePCMData_Internal
// 0x0018 (0x0018 - 0x0000)
struct AsyncRecognizer_RecognizePCMData_Internal final
{
public:
	TArray<uint8>                                 InRawPCMData;                                      // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	uint32                                        InSampleRate;                                      // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_AsyncRecognizer_RecognizePCMData_Internal;

// Function YnnkVoiceLipsync.AsyncRecognizer.IsWorking
// 0x0001 (0x0001 - 0x0000)
struct AsyncRecognizer_IsWorking final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_AsyncRecognizer_IsWorking;

// Function YnnkVoiceLipsync.RecognizePCMData.RecognizeRuntimeSoundWave
// 0x0020 (0x0020 - 0x0000)
struct RecognizePCMData_RecognizeRuntimeSoundWave final
{
public:
	class UObject*                                InWorldContext;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USoundWave*                             InSoundAsset;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptActiveRequest;                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URecognizePCMData*                      ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RecognizePCMData_RecognizeRuntimeSoundWave;

// Function YnnkVoiceLipsync.RecognizePCMData.RecognizeUncompressedPCMData
// 0x0028 (0x0028 - 0x0000)
struct RecognizePCMData_RecognizeUncompressedPCMData final
{
public:
	class UObject*                                InWorldContext;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 InPCMData;                                         // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         InSampleRate;                                      // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptActiveRequest;                           // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class URecognizePCMData*                      ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RecognizePCMData_RecognizeUncompressedPCMData;

// Function YnnkVoiceLipsync.RecognizePCMData.OnAsyncRequestResult
// 0x0018 (0x0018 - 0x0000)
struct RecognizePCMData_OnAsyncRequestResult final
{
public:
	int32                                         ID;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSingeWordData>                 Data;                                              // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RecognizePCMData_OnAsyncRequestResult;

// Function YnnkVoiceLipsync.RemoteRecognizeSoundWave.RemoteRecognizeAudioData
// 0x0028 (0x0028 - 0x0000)
struct RemoteRecognizeSoundWave_RemoteRecognizeAudioData final
{
public:
	class UYnnkRemoteClient*                      RemoteConnectionClient;                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 InPCMData;                                         // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         InSampleRate;                                      // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class URemoteRecognizeSoundWave*              ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RemoteRecognizeSoundWave_RemoteRecognizeAudioData;

// Function YnnkVoiceLipsync.RemoteRecognizeSoundWave.RemoteRecognizeSoundWave
// 0x0018 (0x0018 - 0x0000)
struct RemoteRecognizeSoundWave_RemoteRecognizeSoundWave final
{
public:
	class UYnnkRemoteClient*                      RemoteConnectionClient;                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USoundWave*                             InSoundAsset;                                      // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class URemoteRecognizeSoundWave*              ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RemoteRecognizeSoundWave_RemoteRecognizeSoundWave;

// Function YnnkVoiceLipsync.RemoteRecognizeSoundWave.OnRemoteRequestResult
// 0x0028 (0x0028 - 0x0000)
struct RemoteRecognizeSoundWave_OnRemoteRequestResult final
{
public:
	int32                                         RequestID;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSingeWordData>                 OutSentence;                                       // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class FString                                 Subtitles;                                         // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RemoteRecognizeSoundWave_OnRemoteRequestResult;

// Function YnnkVoiceLipsync.StreamLipsyncGenerator.StartStream
// 0x0001 (0x0001 - 0x0000)
struct StreamLipsyncGenerator_StartStream final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_StreamLipsyncGenerator_StartStream;

// Function YnnkVoiceLipsync.StreamLipsyncGenerator.StreamData
// 0x0010 (0x0010 - 0x0000)
struct StreamLipsyncGenerator_StreamData final
{
public:
	TArray<uint8>                                 Data;                                              // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_StreamLipsyncGenerator_StreamData;

// Function YnnkVoiceLipsync.StreamLipsyncGenerator.IsStreaming
// 0x0001 (0x0001 - 0x0000)
struct StreamLipsyncGenerator_IsStreaming final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_StreamLipsyncGenerator_IsStreaming;

// Function YnnkVoiceLipsync.StreamVoiceRecognizeComponent.FinalizeAudioRecognition
// 0x0018 (0x0018 - 0x0000)
struct StreamVoiceRecognizeComponent_FinalizeAudioRecognition final
{
public:
	class FString                                 JsonData;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFinalized;                                        // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_StreamVoiceRecognizeComponent_FinalizeAudioRecognition;

// Function YnnkVoiceLipsync.StreamVoiceRecognizeComponent.StartCapture
// 0x0018 (0x0018 - 0x0000)
struct StreamVoiceRecognizeComponent_StartCapture final
{
public:
	class FString                                 Message;                                           // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_StreamVoiceRecognizeComponent_StartCapture;

// Function YnnkVoiceLipsync.StreamVoiceRecognizeComponent.StopCapture
// 0x0001 (0x0001 - 0x0000)
struct StreamVoiceRecognizeComponent_StopCapture final
{
public:
	bool                                          bResetVosk;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_StreamVoiceRecognizeComponent_StopCapture;

// Function YnnkVoiceLipsync.StreamVoiceRecognizeComponent.ReadJsonData
// 0x0028 (0x0028 - 0x0000)
struct StreamVoiceRecognizeComponent_ReadJsonData final
{
public:
	bool                                          bFinalResult;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 JsonData;                                          // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutWord;                                           // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_StreamVoiceRecognizeComponent_ReadJsonData;

// Function YnnkVoiceLipsync.YnnkLipsyncController.InitializeAnimationTargets
// 0x0001 (0x0001 - 0x0000)
struct YnnkLipsyncController_InitializeAnimationTargets final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_InitializeAnimationTargets;

// Function YnnkVoiceLipsync.YnnkLipsyncController.OnSpeakerPlaybackPercent
// 0x0010 (0x0010 - 0x0000)
struct YnnkLipsyncController_OnSpeakerPlaybackPercent final
{
public:
	const class USoundWave*                       PlayingSoundWave;                                  // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PlaybackPercent;                                   // 0x0008(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipsyncController_OnSpeakerPlaybackPercent;

// Function YnnkVoiceLipsync.YnnkLipsyncController.OnSpeakerSingleEnvelope
// 0x0010 (0x0010 - 0x0000)
struct YnnkLipsyncController_OnSpeakerSingleEnvelope final
{
public:
	const class USoundWave*                       PlayingSoundWave;                                  // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EnvelopeValue;                                     // 0x0008(0x0004)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipsyncController_OnSpeakerSingleEnvelope;

// Function YnnkVoiceLipsync.YnnkLipsyncController.PrepareSound
// 0x0008 (0x0008 - 0x0000)
struct YnnkLipsyncController_PrepareSound final
{
public:
	class USoundWave*                             Sound;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_PrepareSound;

// Function YnnkVoiceLipsync.YnnkLipsyncController.SetSpeaker
// 0x0008 (0x0008 - 0x0000)
struct YnnkLipsyncController_SetSpeaker final
{
public:
	class UAudioComponent*                        NewSpeaker;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_SetSpeaker;

// Function YnnkVoiceLipsync.YnnkLipsyncController.Speak
// 0x0008 (0x0008 - 0x0000)
struct YnnkLipsyncController_Speak final
{
public:
	class UYnnkVoiceLipsyncData*                  VoiceLipsyncData;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_Speak;

// Function YnnkVoiceLipsync.YnnkLipsyncController.SpeakEx
// 0x0018 (0x0018 - 0x0000)
struct YnnkLipsyncController_SpeakEx final
{
public:
	class USoundBase*                             Voice;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UYnnkVoiceLipsyncData*                  VoiceLipsyncData;                                  // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SoundOffset;                                       // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipsyncController_SpeakEx;

// Function YnnkVoiceLipsync.YnnkLipsyncController.GetCurrentViseme
// 0x0001 (0x0001 - 0x0000)
struct YnnkLipsyncController_GetCurrentViseme final
{
public:
	EYnnkViseme                                   ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_GetCurrentViseme;

// Function YnnkVoiceLipsync.YnnkLipsyncController.IsSpeaking
// 0x0001 (0x0001 - 0x0000)
struct YnnkLipsyncController_IsSpeaking final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipsyncController_IsSpeaking;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.AppendCurveAnimations
// 0x00F0 (0x00F0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_AppendCurveAnimations final
{
public:
	TMap<class FName, struct FSimpleFloatCurve>   A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, struct FSimpleFloatCurve>   B;                                                 // 0x0050(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, struct FSimpleFloatCurve>   Result;                                            // 0x00A0(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_AppendCurveAnimations;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.AppendCurveSet
// 0x00F0 (0x00F0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_AppendCurveSet final
{
public:
	TMap<class FName, float>                      A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      B;                                                 // 0x0050(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      Result;                                            // 0x00A0(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_AppendCurveSet;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.AsyncLoadFromPCMData
// 0x0048 (0x0048 - 0x0000)
struct YnnkLipSyncFunctionLibrary_AsyncLoadFromPCMData final
{
public:
	TArray<uint8>                                 PCMData;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         SampleRate;                                        // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Duration;                                          // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCreateSoundWave;                                  // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptLastRequest;                             // 0x001D(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundWave*                             OutSoundWave;                                      // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 ID, const TArray<struct FSingeWordData>& Data)> CallbackEvent;              // 0x0028(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAsyncRecognizer*                       AsyncRecognizer;                                   // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0040(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_AsyncLoadFromPCMData;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.ConnectToRecognitionServer
// 0x0020 (0x0020 - 0x0000)
struct YnnkLipSyncFunctionLibrary_ConnectToRecognitionServer final
{
public:
	class FString                                 IPv4;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Port;                                              // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLogData;                                          // 0x0014(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UYnnkRemoteClient*                      ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_ConnectToRecognitionServer;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.CreateLipsyncDataFromWavFile
// 0x0048 (0x0048 - 0x0000)
struct YnnkLipSyncFunctionLibrary_CreateLipsyncDataFromWavFile final
{
public:
	class UObject*                                WorldContext;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Filename;                                          // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(class UYnnkVoiceLipsyncData* VoiceLipsyncData, bool bResult, const class FString& Subtitles)> CallbackEvent; // 0x0018(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptLastRequest;                             // 0x0028(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 OutErrors;                                         // 0x0030(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_CreateLipsyncDataFromWavFile;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.CreateTranscriptedTextFromFile
// 0x0040 (0x0040 - 0x0000)
struct YnnkLipSyncFunctionLibrary_CreateTranscriptedTextFromFile final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 ID, const TArray<struct FSingeWordData>& Data)> CallbackEvent;              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptLastRequest;                             // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundWave*                             LoadedAudio;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAsyncRecognizer*                       AsyncRecognizer;                                   // 0x0030(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0038(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_CreateTranscriptedTextFromFile;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.CreateTranscriptedTextFromSpeechAsset
// 0x0020 (0x0020 - 0x0000)
struct YnnkLipSyncFunctionLibrary_CreateTranscriptedTextFromSpeechAsset final
{
public:
	class USoundWave*                             SpeechAudio;                                       // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseRawPCMData;                                    // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(int32 ID, const TArray<struct FSingeWordData>& Data)> CallbackEvent;              // 0x000C(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInterruptLastRequest;                             // 0x001C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         ReturnValue;                                       // 0x001D(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_CreateTranscriptedTextFromSpeechAsset;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.CreateTranscriptionDictionary
// 0x0030 (0x0030 - 0x0000)
struct YnnkLipSyncFunctionLibrary_CreateTranscriptionDictionary final
{
public:
	class FString                                 DictFile_ARPAbet;                                  // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 StartAt;                                           // 0x0010(0x0010)(ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 TargetFileName;                                    // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_CreateTranscriptionDictionary;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.ExpandCurveToBaseCurves
// 0x00C0 (0x00C0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_ExpandCurveToBaseCurves final
{
public:
	struct FSimpleFloatCurve                      InCurve;                                           // 0x0000(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TSet<class FName>                             AnimationTargets;                                  // 0x0018(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	const class UPoseAsset*                       PoseAsset;                                         // 0x0068(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FName, struct FSimpleFloatCurve>   OutCurves;                                         // 0x0070(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_ExpandCurveToBaseCurves;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.ExpandPoseAnimationToCurves
// 0x00C0 (0x00C0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_ExpandPoseAnimationToCurves final
{
public:
	TMap<class FName, struct FSimpleFloatCurve>   InAnimation;                                       // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	const class UPoseAsset*                       PoseAsset;                                         // 0x0050(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FName, struct FSimpleFloatCurve>   OutAnimation;                                      // 0x0058(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
	class FString                                 CurveNameFilter;                                   // 0x00A8(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CombineKeysPrecision;                              // 0x00B8(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOptimizeKeys;                                     // 0x00BC(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_ExpandPoseAnimationToCurves;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.GetCurvesSetDuration
// 0x0058 (0x0058 - 0x0000)
struct YnnkLipSyncFunctionLibrary_GetCurvesSetDuration final
{
public:
	TMap<class FName, struct FSimpleFloatCurve>   CurvesAnimation;                                   // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x0050(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_GetCurvesSetDuration;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.GetLipsyncGenerationLangualge
// 0x0010 (0x0010 - 0x0000)
struct YnnkLipSyncFunctionLibrary_GetLipsyncGenerationLangualge final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_GetLipsyncGenerationLangualge;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.GetSimpleCurveValue
// 0x0020 (0x0020 - 0x0000)
struct YnnkLipSyncFunctionLibrary_GetSimpleCurveValue final
{
public:
	struct FSimpleFloatCurve                      Curve;                                             // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_GetSimpleCurveValue;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.LoadWaveFile
// 0x0030 (0x0030 - 0x0000)
struct YnnkLipSyncFunctionLibrary_LoadWaveFile final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<uint8>                                 OutPCMData;                                        // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         SampleRate;                                        // 0x0020(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x0024(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Channels;                                          // 0x0025(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Duration;                                          // 0x0028(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x002C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_LoadWaveFile;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.LoadWaveFileToSoundWave
// 0x0028 (0x0028 - 0x0000)
struct YnnkLipSyncFunctionLibrary_LoadWaveFileToSoundWave final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                Outer_0;                                           // 0x0010(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USoundWave*                             OutSoundWave;                                      // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_LoadWaveFileToSoundWave;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.MultiplyCurvesSet
// 0x00A8 (0x00A8 - 0x0000)
struct YnnkLipSyncFunctionLibrary_MultiplyCurvesSet final
{
public:
	TMap<class FName, float>                      A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         Multiplier;                                        // 0x0050(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, float>                      Result;                                            // 0x0058(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_MultiplyCurvesSet;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.MultiplyCurvesSets
// 0x00F0 (0x00F0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_MultiplyCurvesSets final
{
public:
	TMap<class FName, float>                      A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      B;                                                 // 0x0050(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      Result;                                            // 0x00A0(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_MultiplyCurvesSets;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.PowerCurvesSet
// 0x00A8 (0x00A8 - 0x0000)
struct YnnkLipSyncFunctionLibrary_PowerCurvesSet final
{
public:
	TMap<class FName, float>                      A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         B;                                                 // 0x0050(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FName, float>                      Result;                                            // 0x0058(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_PowerCurvesSet;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.RecognizeRawAudioData
// 0x0028 (0x0028 - 0x0000)
struct YnnkLipSyncFunctionLibrary_RecognizeRawAudioData final
{
public:
	TArray<uint8>                                 PCMData;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	uint8                                         BitRate;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FSingeWordData>                 OutRecognizedData;                                 // 0x0018(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_RecognizeRawAudioData;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.SaveSoundWaveToFile
// 0x0018 (0x0018 - 0x0000)
struct YnnkLipSyncFunctionLibrary_SaveSoundWaveToFile final
{
public:
	class USoundWave*                             Wave;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Filename;                                          // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_SaveSoundWaveToFile;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.SetYnnkAudioSampleRate
// 0x0004 (0x0004 - 0x0000)
struct YnnkLipSyncFunctionLibrary_SetYnnkAudioSampleRate final
{
public:
	int32                                         NewSampleRate;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_SetYnnkAudioSampleRate;

// Function YnnkVoiceLipsync.YnnkLipSyncFunctionLibrary.SubstractCurvesSet
// 0x00F0 (0x00F0 - 0x0000)
struct YnnkLipSyncFunctionLibrary_SubstractCurvesSet final
{
public:
	TMap<class FName, float>                      A;                                                 // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      B;                                                 // 0x0050(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	TMap<class FName, float>                      Result;                                            // 0x00A0(0x0050)(Parm, OutParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkLipSyncFunctionLibrary_SubstractCurvesSet;

// Function YnnkVoiceLipsync.YnnkRemoteClient.ConnectToServer
// 0x0018 (0x0018 - 0x0000)
struct YnnkRemoteClient_ConnectToServer final
{
public:
	class FString                                 IP;                                                // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Port;                                              // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkRemoteClient_ConnectToServer;

// Function YnnkVoiceLipsync.YnnkRemoteClient.GenerateFacialAnimation
// 0x0010 (0x0010 - 0x0000)
struct YnnkRemoteClient_GenerateFacialAnimation final
{
public:
	const class UYnnkVoiceLipsyncData*            LipsyncData;                                       // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLipSync;                                          // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bFacialAnimation;                                  // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ReturnValue;                                       // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkRemoteClient_GenerateFacialAnimation;

// Function YnnkVoiceLipsync.YnnkRemoteClient.RecognizeAudioData
// 0x0028 (0x0028 - 0x0000)
struct YnnkRemoteClient_RecognizeAudioData final
{
public:
	TArray<uint8>                                 PCMData;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         SampleRate;                                        // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 RequestID, const TArray<struct FSingeWordData>& OutSentence, const class FString& Subtitles)> CallbackEvent; // 0x0014(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0024(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkRemoteClient_RecognizeAudioData;

// Function YnnkVoiceLipsync.YnnkRemoteClient.RecognizeSoundWave
// 0x0020 (0x0020 - 0x0000)
struct YnnkRemoteClient_RecognizeSoundWave final
{
public:
	class USoundWave*                             SoundAsset;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TDelegate<void(int32 RequestID, const TArray<struct FSingeWordData>& OutSentence, const class FString& Subtitles)> CallbackEvent; // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0018(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkRemoteClient_RecognizeSoundWave;

// Function YnnkVoiceLipsync.YnnkRemoteClient.IsConnected
// 0x0001 (0x0001 - 0x0000)
struct YnnkRemoteClient_IsConnected final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkRemoteClient_IsConnected;

// Function YnnkVoiceLipsync.YnnkRemoteClient.IsInitialized
// 0x0001 (0x0001 - 0x0000)
struct YnnkRemoteClient_IsInitialized final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkRemoteClient_IsInitialized;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.CreateVoiceLipsyncData
// 0x0028 (0x0028 - 0x0000)
struct YnnkVoiceLipsyncData_CreateVoiceLipsyncData final
{
public:
	class UObject*                                Parent;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSingeWordData>                 Sentence;                                          // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class USoundWave*                             VoiceSound;                                        // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UYnnkVoiceLipsyncData*                  ReturnValue;                                       // 0x0020(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_CreateVoiceLipsyncData;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.CreateVoiceLipsyncDataEx
// 0x0030 (0x0030 - 0x0000)
struct YnnkVoiceLipsyncData_CreateVoiceLipsyncDataEx final
{
public:
	class UObject*                                Parent;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSingeWordData>                 Sentence;                                          // 0x0008(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	class USoundWave*                             VoiceSound;                                        // 0x0018(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bStretchCurves;                                    // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bForceGeneratePhonemes;                            // 0x0021(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UYnnkVoiceLipsyncData*                  ReturnValue;                                       // 0x0028(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_CreateVoiceLipsyncDataEx;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.ConvertAnimationToBaseCurves
// 0x0060 (0x0060 - 0x0000)
struct YnnkVoiceLipsyncData_ConvertAnimationToBaseCurves final
{
public:
	const class UPoseAsset*                       PoseAsset;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<EYnnkViseme, struct FCompositeCurvesWrapper> AnimationTargets;                              // 0x0008(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         SmoothAlpha;                                       // 0x0058(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_ConvertAnimationToBaseCurves;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.CreateCurves
// 0x0010 (0x0010 - 0x0000)
struct YnnkVoiceLipsyncData_CreateCurves final
{
public:
	TArray<struct FSingeWordData>                 Sentence;                                          // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_CreateCurves;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.GetCurveValue
// 0x0020 (0x0020 - 0x0000)
struct YnnkVoiceLipsyncData_GetCurveValue final
{
public:
	struct FSimpleFloatCurve                      Curve;                                             // 0x0000(0x0018)(Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         Time;                                              // 0x0018(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ReturnValue;                                       // 0x001C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_GetCurveValue;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.ContainsData
// 0x0001 (0x0001 - 0x0000)
struct YnnkVoiceLipsyncData_ContainsData final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_ContainsData;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.GetAnimationStartTime
// 0x0004 (0x0004 - 0x0000)
struct YnnkVoiceLipsyncData_GetAnimationStartTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_GetAnimationStartTime;

// Function YnnkVoiceLipsync.YnnkVoiceLipsyncData.GetDuration
// 0x0004 (0x0004 - 0x0000)
struct YnnkVoiceLipsyncData_GetDuration final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_YnnkVoiceLipsyncData_GetDuration;

}

